# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videocategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocategory',
            name='video',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
