# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20171130_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetitem',
            name='snippet_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='video_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
