# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20171230_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.SET_DEFAULT, to='categories.VideoCategory'),
        ),
    ]
