# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20171130_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetitem',
            old_name='snippet_id',
            new_name='snippet_video_id',
        ),
    ]
