# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20171203_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetitem',
            old_name='snippet_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='snippetitem',
            old_name='snippet_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='snippetitem',
            old_name='snippet_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='snippetitem',
            old_name='snippet_video_id',
            new_name='video_id',
        ),
        migrations.RenameField(
            model_name='videoitem',
            old_name='video_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='videoitem',
            old_name='video_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='videoitem',
            old_name='video_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='videoitem',
            old_name='video_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='videoitem',
            old_name='video_user_id',
            new_name='user_id',
        ),
    ]
