# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20171230_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='yt_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
