# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20171204_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetitem',
            name='end',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='snippetitem',
            name='start',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)]),
        ),
    ]
