# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20171204_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetitem',
            name='end',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='snippetitem',
            name='start',
            field=models.FloatField(default=0),
        ),
    ]
