# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20171204_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetitem',
            name='start',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='start',
            field=models.FloatField(),
        ),
    ]
