# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20171204_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetitem',
            name='end',
        ),
        migrations.RemoveField(
            model_name='snippetitem',
            name='start',
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='start',
            field=models.FloatField(default=0),
        ),
    ]
