# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20171204_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetitem',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='videoitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
