# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20171205_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetitem',
            name='jump',
            field=models.FloatField(default=2),
        ),
    ]
