# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_snippetitem_jump'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
