# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_videoitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetitem',
            name='video',
        ),
        migrations.DeleteModel(
            name='SnippetItem',
        ),
    ]
