# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20171212_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='yt_id',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
