# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_videoitem_yt_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoItem',
            new_name='Video',
        ),
    ]
