# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20171208_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
