# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_auto_20171208_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='start_date',
        ),
    ]
