# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_remove_subscriptiontype_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
