# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sub_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
