# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171130_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sub_type',
            field=models.IntegerField(default=1),
        ),
    ]
