# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171130_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sub_nextreset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub_type',
            field=models.IntegerField(default=0),
        ),
    ]
