# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180107_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
