# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180106_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocategory',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
    ]
