# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosnippets', '0002_auto_20171220_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='end',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='jump',
            field=models.FloatField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='start',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
